version: 0.0
os: Linux
files:
  - source: /
    destination: /home/ubuntu/deploy/
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/deploy/
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
