name: Backend Build and Push (For main)

on: # 워크플로우가 언제 실행되는지 정의 (like 조건문)
  push:
    branches:
      - SJ-67--build-CI-pipeline # 지정한 브랜치로 Push 했을 때
    paths:
      - 'src/**'
  pull_request:
    branches:
      - SJ-67--build-CI-pipeline # 테스트용 임시 브랜치

jobs: # 해당 워크플로우에서 어떤 일이 수행되어야 하는지 정의 (like 조건문의 본문)
  image-build-and-push:
    # 가장 최신 버전의 우분투를 러너(Github Actions 실행 환경)로 설정
    runs-on: ubuntu-latest # 상세 작업에 필수적으로 들어가야 하는 항목 : 어느 환경에서 실행되어야 하는지 정의

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 현재 리포지토리로 체크아웃

      - name: Set up Docker Buildx # 멀티 플랫폼 빌드와 캐시 활용을 할 수 있는 도커 빌드X 설치
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Github Secret에서 Docker hub 사용자 이름을 가져옴
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Github Secret에서 Docker hub 액세스 토큰을 가져옴
